#############################################################################
# Makefile for building: libQtSign.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 1? 17 10:02:11 2023
# Project:  QtSignLib.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile QtSignLib.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQTSIGNLIB_LIBRARY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -Wl,-rpath=./ -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/wenyu/code/test/qt/2/QtSignLib/ -shared -Wl,-soname,libQtSign.so.1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = QCertEsealDialog/QCertEsealDialog.cpp \
		qtsignlib.cpp moc_QCertEsealDialog.cpp \
		qrc_QtSignLibResource.cpp
OBJECTS       = QCertEsealDialog.o \
		qtsignlib.o \
		moc_QCertEsealDialog.o \
		qrc_QtSignLibResource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/dll.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QtSignLib.pro
QMAKE_TARGET  = QtSign
DESTDIR       = 
TARGET        = libQtSign.so.1.0.0
TARGETA       = libQtSign.a
TARGETD       = libQtSign.so.1.0.0
TARGET0       = libQtSign.so
TARGET1       = libQtSign.so.1
TARGET2       = libQtSign.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: QtSignLib.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/dll.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile QtSignLib.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/dll.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QtSignLib.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QtSign1.0.0 || $(MKDIR) .tmp/QtSign1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QtSign1.0.0/ && $(COPY_FILE) --parents QCertEsealDialog/CertEsealStruct.h QCertEsealDialog/QCertEsealDialog.h QtSignLib_global.h qtsignlib.h .tmp/QtSign1.0.0/ && $(COPY_FILE) --parents QtSignLibResource.qrc .tmp/QtSign1.0.0/ && $(COPY_FILE) --parents QCertEsealDialog/QCertEsealDialog.cpp qtsignlib.cpp .tmp/QtSign1.0.0/ && (cd `dirname .tmp/QtSign1.0.0` && $(TAR) QtSign1.0.0.tar QtSign1.0.0 && $(COMPRESS) QtSign1.0.0.tar) && $(MOVE) `dirname .tmp/QtSign1.0.0`/QtSign1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtSign1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_QCertEsealDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QCertEsealDialog.cpp
moc_QCertEsealDialog.cpp: QCertEsealDialog/CertEsealStruct.h \
		QCertEsealDialog/QCertEsealDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QCertEsealDialog/QCertEsealDialog.h -o moc_QCertEsealDialog.cpp

compiler_rcc_make_all: qrc_QtSignLibResource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_QtSignLibResource.cpp
qrc_QtSignLibResource.cpp: QtSignLibResource.qrc \
		resource/icon/stamp_icon.png \
		resource/icon/USB_app_flash_drive_icon.png \
		resource/icon/upload_cloud_icon.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name QtSignLibResource QtSignLibResource.qrc -o qrc_QtSignLibResource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

QCertEsealDialog.o: QCertEsealDialog/QCertEsealDialog.cpp QCertEsealDialog/QCertEsealDialog.h \
		QCertEsealDialog/CertEsealStruct.h \
		qtsignlib.h \
		QtSignLib_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QCertEsealDialog.o QCertEsealDialog/QCertEsealDialog.cpp

qtsignlib.o: qtsignlib.cpp qtsignlib.h \
		QtSignLib_global.h \
		QCertEsealDialog/QCertEsealDialog.h \
		QCertEsealDialog/CertEsealStruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsignlib.o qtsignlib.cpp

moc_QCertEsealDialog.o: moc_QCertEsealDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QCertEsealDialog.o moc_QCertEsealDialog.cpp

qrc_QtSignLibResource.o: qrc_QtSignLibResource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_QtSignLibResource.o qrc_QtSignLibResource.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/wenyu/code/test/qt/2/QtSignLib/./ || $(MKDIR) $(INSTALL_ROOT)/home/wenyu/code/test/qt/2/QtSignLib/./ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/$(TARGET2)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/wenyu/code/test/qt/2/QtSignLib/./ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

